services:
  - type: web
    name: bag-price-project
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install --with-deps chromium
    startCommand: gunicorn app:app --timeout 300